version: '3'

services:
  postgres:
    container_name: storage_bet
    env_file:
      - .env
    hostname: ${STORAGE_BET__HOST}
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${STORAGE_BET__USER}
      - POSTGRES_PASSWORD=${STORAGE_BET__PASSWORD}
      - POSTGRES_DB=${STORAGE_BET__DBNAME}
    ports:
      - "5432:5432"
    expose:
      - ${STORAGE_BET__PORT}