"""initial

Revision ID: ff37fa3d4111
Revises: 
Create Date: 2023-04-07 00:50:15.330113

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff37fa3d4111"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet",
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("money", sa.Float(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_insert", sa.DateTime(), nullable=True),
        sa.Column("date_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    # ### end Alembic commands ###
