"""create base structure

Revision ID: be435864df3e
Revises: 
Create Date: 2023-07-09 14:44:26.361398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be435864df3e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_state",
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_insert", sa.DateTime(), nullable=True),
        sa.Column("date_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("coefficient", sa.DECIMAL(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=False),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_insert", sa.DateTime(), nullable=True),
        sa.Column("date_update", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["event_state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("event_state")
    # ### end Alembic commands ###
